//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityTest.Models.Entities
{
	using System;
	using System.Collections.Generic;

	public partial class Answer
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public Answer()
		{
			this.ResultInfoes = new HashSet<ResultInfo>();
		}

		public int ID { get; set; }
		public int Number { get; set; }
		public string Content { get; set; }
		public bool IsCorrect { get; set; }
		public string Correct => IsCorrect ? "Верный" : "";
		public Nullable<int> IDQuestion { get; set; }

		public virtual Question Question { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<ResultInfo> ResultInfoes { get; set; }
	}
}
