//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityTest.Models.Entities
{
	using System;
	using System.Data.Entity;
	using System.Data.Entity.Infrastructure;

	public partial class SecurityEntities : DbContext
	{
		private static SecurityEntities _ctx;

		public static SecurityEntities GetContext()
		{
			if (_ctx == null)
				_ctx = new SecurityEntities();
			return _ctx;
		}
		public SecurityEntities()
						: base("name=SecurityEntities")
		{
		}

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
		{
			throw new UnintentionalCodeFirstException();
		}

		public virtual DbSet<Answer> Answers { get; set; }
		public virtual DbSet<Exam> Exams { get; set; }
		public virtual DbSet<Question> Questions { get; set; }
		public virtual DbSet<Result> Results { get; set; }
		public virtual DbSet<ResultInfo> ResultInfoes { get; set; }
		public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
		public virtual DbSet<Test> Tests { get; set; }
		public virtual DbSet<Theme> Themes { get; set; }
		public virtual DbSet<User> Users { get; set; }
		public virtual DbSet<UserInfo> UserInfoes { get; set; }
	}
}
