//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityTest.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int ID { get; set; }
        public int IDUser { get; set; }
        public int IDTest { get; set; }
        public Nullable<bool> IsTime { get; set; }
        public Nullable<int> TimeInSecond { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
    }
}
